import type { AnalyzeResult, AuditCategory, AuditFinding } from "../../types/api";

const categoryLabels: Record<AuditCategory, string> = {
  community: "Community readiness",
  "developer-experience": "Developer experience",
  testing: "Testing and automation",
  maintainability: "Maintainability",
  "frontend-quality": "Frontend quality",
};

function findingMarkdown(finding: AuditFinding): string {
  const evidence = finding.evidence
    .map((item) => {
      const location = item.location
        ? ` — \`${item.location.file}${item.location.lineStart ? `:${item.location.lineStart}` : ""}\``
        : "";
      return `- **${item.label}:** ${item.value}${location}`;
    })
    .join("\n");
  const files = finding.files.length
    ? `\n**Files:** ${finding.files.map((file) => `\`${file}\``).join(", ")}\n`
    : "";
  return `### ${finding.title}

- Severity: **${finding.severity}**
- Confidence: **${finding.confidence}**
- Difficulty: **${finding.difficulty}**

${finding.summary}

**Why it matters:** ${finding.whyItMatters}

**Recommended action:** ${finding.recommendation}
${files}
**Evidence**

${evidence}

**Contribution task**

> ${finding.contributionTask}${finding.limitation ? `\n\n_Limitation: ${finding.limitation}_` : ""}`;
}

export function createAuditMarkdown(analysis: AnalyzeResult): string {
  const { audit } = analysis;
  const categoryScores = audit.categoryScores
    .map((item) => `- ${categoryLabels[item.category]}: **${item.score}/100** (${item.findingCount} findings)`)
    .join("\n");
  const findings = audit.findings.length
    ? audit.findings.map(findingMarkdown).join("\n\n")
    : "No actionable findings were produced by the current audit rules.";
  const strengths = audit.strengths.length
    ? audit.strengths.map((item) => `- **${item.title}:** ${item.evidence}`).join("\n")
    : "- No verified strengths were recorded.";
  const skipped = audit.coverage.skippedFiles.length
    ? audit.coverage.skippedFiles
        .map((file) => `- \`${file.path}\` — ${file.reason}, ${Math.round(file.size / 1024)} KB`)
        .join("\n")
    : "- None";
  const limitations = audit.coverage.limitations.map((item) => `- ${item}`).join("\n");

  return `# RepoLens audit: ${analysis.name}

Repository: ${analysis.repoUrl}<br>
Generated: ${audit.generatedAt}

## Start here

**Readiness:** ${audit.status.replaceAll("-", " ")}<br>
**Score:** ${audit.score}/100<br>
**Summary:** ${audit.headline}

${audit.summary}

## Category scores

${categoryScores}

## Analysis coverage

- Repository files reported: ${audit.coverage.repositoryFiles}
- Supported files: ${audit.coverage.supportedFiles}
- Files fetched: ${audit.coverage.fetchedFiles}
- Parsed source files: ${audit.coverage.analyzedSourceFiles}
- Supported-file coverage: ${audit.coverage.coveragePercent}%

### Skipped files

${skipped}

### Limitations

${limitations}

## Prioritized findings

${findings}

## Verified strengths

${strengths}

## Contribution opportunities

${audit.opportunities.length
  ? audit.opportunities.map((item, index) => `${index + 1}. **${item.title}** (${item.difficulty})\n   ${item.task}`).join("\n")
  : "No contribution opportunities were generated by the current rules."}
`;
}
